// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpwivlstdqvesspobmdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwd2l2bHN0ZHF2ZXNzcG9ibWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTcxOTIsImV4cCI6MjA3MDkzMzE5Mn0.Auz6ZGF6N76EkEJxuvdEXXu5Hv9_172NfCnuuhU3ftk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});